#######################
## DOCKERFILE-1
#######################
#NOTE: This image uses the Jetbrains JVM which is somewhat problematic.
# image: nfcore/gitpod:latest

# tasks:
#   - name: Install graphviz
#     init: pip install graphviz

#######################
## DOCKERFILE-2
#######################

# image:
#   file: .gitpod.Dockerfile

image: rg.nl-ams.scw.cloud/course-containers/bioinfo-gitpod:22.09.7

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:

  # - name: Install utilities and setup Singularity
  #   command: |
  #     sudo apt install  -y graphviz aria2c
  #     brew install rclone tealdeer go
  #     tldr -u

  #     sudo apt-get update && \
  #     sudo apt-get install -y build-essential \
  #     libseccomp-dev pkg-config squashfs-tools cryptsetup

  #     mkdir -p ${GOPATH}/src/github.com/sylabs && \
  #     cd ${GOPATH}/src/github.com/sylabs && \
  #     git clone https://github.com/sylabs/singularity.git && \
  #     cd singularity

  #     git checkout v3.6.3

  #     cd ${GOPATH}/src/github.com/sylabs/singularity && \
  #     ./mconfig  --without-suid && \
  #     cd ./builddir && \
  #     make && \
  #     sudo make install
  #     exit

  - name: Nextflow terminal
    init: |
      echo 'init script' # runs during prebuild
      echo 'start script'
    command: |
      export NXF_EDGE=0
      export NXF_VER=22.10.2
      echo 'export NXF_EDGE=0' >> $HOME/.bashrc
      echo 'export NXF_VER=22.10.2' >> $HOME/.bashrc
      curl -s https://get.nextflow.io | bash
      chmod +x nextflow
      sudo mv nextflow /usr/local/bin/
      nextflow self-update
      unset JAVA_TOOL_OPTIONS
      alias conda_activate="source /opt/conda/etc/profile.d/conda.sh; conda activate base"
      printf 'source /opt/conda/etc/profile.d/conda.sh; conda activate base\n' >> $HOME/.bashrc
      printf 'alias conda_activate=\"source /opt/conda/etc/profile.d/conda.sh; conda activate base\"\n' >> $HOME/.bashrc

  # - name: Download datasets
  #   command: |
  #     bash /workspace/bioinfo-gitpod/datasets/download_datasets.sh
  #     unset JAVA_TOOL_OPTIONS
  #     alias conda_activate="source /opt/conda/etc/profile.d/conda.sh; conda activate base"



vscode:
  extensions:
    - codezombiech.gitignore                 # Language support for .gitignore files
    - davidanson.vscode-markdownlint         # Markdown/CommonMark linting and style checking for Visual Studio Code
    - Gruntfuggly.todo-tree                  # Display TODO and FIXME in a tree view in the activity bar
    - mechatroner.rainbow-csv                # Highlight columns in csv files in different colors
    - oderwat.indent-rainbow                 # Highlight indentation level
    - streetsidesoftware.code-spell-checker  # Spelling checker for source code
    - anwar.papyrus-pdf                      # PDF preview
    - ms-vscode.live-server                  # Live server
